table Details
	lineageTag: 7cc62760-0aef-40d4-89f3-b527e9ea02bd

	column 'Order ID'
		dataType: string
		lineageTag: ef78cbdd-d4bb-4b94-849b-cc47b8d5708b
		summarizeBy: none
		sourceColumn: Order ID

		annotation SummarizationSetBy = Automatic

	column Amount
		dataType: int64
		formatString: 0
		lineageTag: c9b4830b-6547-4602-860b-d1b32c950e60
		summarizeBy: sum
		sourceColumn: Amount

		annotation SummarizationSetBy = Automatic

	column Profit
		dataType: int64
		formatString: 0
		lineageTag: a959ff52-c1f6-43de-aa21-a02167d60de6
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: f459a754-846e-46c6-9a15-5d092e1044cd
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 1419e871-a189-436f-9655-6648762f0869
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Sub-Category
		dataType: string
		lineageTag: 17e765ea-1f9b-4009-988c-c46f41847d85
		summarizeBy: none
		sourceColumn: Sub-Category

		annotation SummarizationSetBy = Automatic

	column PaymentMode
		dataType: string
		lineageTag: 8012ea0b-b680-4350-9119-71738b3ec709
		summarizeBy: none
		sourceColumn: PaymentMode

		annotation SummarizationSetBy = Automatic

	column AVG = ```
			Details[Amount]/[Quantity] 
			```
		dataType: int64
		lineageTag: fcfc49df-1d37-41ed-9761-65f4d24b693c
		summarizeBy: sum

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Details = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\vishw\Downloads\Details.csv"),[Delimiter=",", Columns=7, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Order ID", type text}, {"Amount", Int64.Type}, {"Profit", Int64.Type}, {"Quantity", Int64.Type}, {"Category", type text}, {"Sub-Category", type text}, {"PaymentMode", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

