table Orders
	lineageTag: f9799dd6-0dd0-4c86-a18b-bdd02be7c2c4

	column 'Order ID'
		dataType: string
		lineageTag: 963a723e-6292-435c-8faa-29e96f632d9e
		summarizeBy: none
		sourceColumn: Order ID

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 91cead0d-0545-4617-949c-e04ad6b3617e
		summarizeBy: none
		sourceColumn: Order Date

		variation Variation
			isDefault
			relationship: 2f7ad46c-3e72-418c-bbe5-7e654d274222
			defaultHierarchy: LocalDateTable_38cdd17f-774a-4483-a00d-836f1a1fc43e.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column CustomerName
		dataType: string
		lineageTag: af237007-44f1-4b0c-9193-daf40b6b24c3
		summarizeBy: none
		sourceColumn: CustomerName

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: 23470ed1-34a0-41d5-bb3e-dec4792e3dc8
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: b8a6f1dd-a73d-41be-9ccc-f48476371583
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	partition Orders = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\vishw\Downloads\Orders.csv"),[Delimiter=",", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Order ID", type text}, {"Order Date", type date}, {"CustomerName", type text}, {"State", type text}, {"City", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

